### ISSUE TITLE
No packages available

### ISSUE THREAD

**Issue by mvitz** [foojayio/discoapi#101]
Currently, the API seems not to return any package

```
$ curl https://api.foojay.io/disco/v3.0/packages/all
{"result":[],"message":""}
```

Is this a failure or intented?

I noticed it because my jbang action during build could not download any JDK and therefore failed.

Thanks for your time and effort :-)

**Comment by HanSolo** [comment]
Nope that's not normal...we are looking into it, thanks for the heads up 👍🏻

**Comment by HanSolo** [comment]
Should be back online again...
