### ISSUE TITLE
Incorrect JDK For Windows, Oracle Open JDK, 8.0.342

### ISSUE THREAD

**Issue by patrick-mccourt** [foojayio/discoapi#104]
Hi, 

I'm a maintainer over at https://github.com/Jabba-Team and a user has raised an issue installing Windows Openjdk 8.0.342, trying to figure out if I'm parsing the results from the API incorrectly. 

I look at the [pkg download redirect](https://github.com/Jabba-Team/index/blob/main/index.json#L1880) I have for Windows, Oracle Open jdk,  8.0.342 and it seems to point to a java 11 jdk.

Looking into where I could've gotten that from I see that for Windows, version 8.0.342, oracle openjdk I see there's two packages returned

https://api.foojay.io/disco/v3.0/packages/jdks?version=8.0.342&distribution=oracle_open_jdk&operating_system=windows

One of which has the filename  `"OpenJDK11U-jre-shenandoa…nux_11.0.11_5_ea.tar.gz"` Should this be returned for the above api call?

**Comment by HanSolo** [comment]
Thanks for the heads up, will take a look at it asap 👍🏻
