### ISSUE TITLE
Linux on s390x: No JDK available for AOJ, AOJ_J9, Semeru, SemeruCertified and Temurin

### ISSUE THREAD

**Issue by hfhbd** [foojayio/discoapi#105]
Hey,

when I use this request, I only get some non-downloadable Debian result, but there is a JDK for Linux on s390x available by AOJ, AOJ_J9, Semeru, SemeruCertified and Temurin.

`https://api.foojay.io/disco/v3.0/packages?version=21&architecture=s390x&operating_system=linux`

AOJ, AOJ_J9: https://adoptopenjdk.net/releases.html
Semeru, SemeruCertified: https://developer.ibm.com/languages/java/semeru-runtimes/downloads/
Temurin: https://adoptium.net/de/temurin/releases/?arch=s390x

I did try to fork and update the code, but only AOJ, AOJ_J9 and Temurin had an explicit arch mapping.

**Comment by HanSolo** [comment]
When you search for the latest available version for a major version e.g. 21, the following call will give you the result you are looking for: [https://api.foojay.io/disco/v3.0/packages/jdks?jdk_version=21&operating_system=linux&architecture=s390x&latest=available](https://api.foojay.io/disco/v3.0/packages/jdks?jdk_version=21&operating_system=linux&architecture=s390x&latest=available)

**Comment by hfhbd** [comment]
Thanks, then I'll further investigate why the Gradle plugin does not resolve the JDK for s390x, though it's caused by the API.
