### ISSUE TITLE
oracle distros < 17 disapperared

### ISSUE THREAD

**Issue by marchof** [foojayio/discoapi#42]
Hi, it looks like the `oracle` distros disappeared. In particular the following queries only returns Java 17 packages:

https://api.foojay.io/disco/v2.0/packages?distro=oracle

These queries now return empty results:

https://api.foojay.io/disco/v2.0/packages?version=11&distro=oracle

**Comment by marchof** [comment]
Interestingly this endpoint still reports that the versions are available:

https://api.foojay.io/disco/v2.0/distributions

**Comment by HanSolo** [comment]
The problem is related to the fact that now Oracle also offers packages that are directly downloadable. As a workaround you might want to use: 

Not directly downloadable: https://api.foojay.io/disco/v2.0/packages?distro=oracle&directly_downloadable=false

Directly downloadable: https://api.foojay.io/disco/v2.0/packages?distro=oracle&directly_downloadable=true

I will look into this asap, thx for the heads up.

**Comment by marchof** [comment]
Thanks!

BTW, same problem with `redhat`

**Comment by HanSolo** [comment]
ok...will check that too 👍🏻

**Comment by HanSolo** [comment]
With the latest deployment the following calls should work as expected:
https://api.foojay.io/disco/v2.0/packages?distro=oracle
https://api.foojay.io/disco/v2.0/packages?distro=redhat

When calling:
https://api.foojay.io/disco/v2.0/packages?version=11&distro=oracle

You need to add ?latest=all_of_version as follows:
https://api.foojay.io/disco/v2.0/packages?version=11&distro=oracle&latest=all_of_version

**Comment by marchof** [comment]
@HanSolo So you mean I should now use `latest=all_of_version` instead of `latest=available`? Does it then return the same results as before?

**Comment by marchof** [comment]
`latest=all_of_version` does something different: It lists all update versions, not just the current.

What is the new API to get the latest version of a specific feature release and distribution?

**Comment by HanSolo** [comment]
Ok, so I thought by asking just for 11 with https://api.foojay.io/v2.0/packages?version=11&distro=oracle you would like to see all available version of JDK 11 from Oracle and for this you need to add &latest=all_of_version.
If you would like to see the latest version of a specific feature release and distribution it is &latest=available (which is 11.0.12 for Oracle JDKs).

**Comment by marchof** [comment]
I can confirm

  https://api.foojay.io/disco/v2.0/packages?version=11&distro=oracle&latest=available

works again as expected. Thanks!
