### ISSUE TITLE
Current API state and question about guidance for usage in client applications

### ISSUE THREAD

**Issue by repolevedavaj** [foojayio/discoapi#44]
I am currently checking whether I can use the DiscoAPI as a replacement for my current solution which I use to resolve the download URL for a specific JDK distribution. 

During the creation of some unit tests I discovered, that the API does not seem stable:
First I call the `/disco/v2.0/packages/jdks` endpoint to get an ephemeral id. Afterwards, I call the endpoint `/disco/v2.0/ephemeral_ids/{ephemeral_id}` to get the download URL. 
I created unit tests for different versions of the Temurin and GraalVM distribution. Sometimes they work and sometimes they fail. I already validated that the call does not fail because of a timeout. It seems that I sometimes get already expired id's. Sometimes I even get an empty result after calling the `/disco/v2.0/packages/jdks` endpoint.

Is there a known issue, or is the API still under construction? I would like to use the API in a client library and do not have any backend which I can use to cache the results from your API to overcome such issues.

Thanks in advance.

**Comment by HanSolo** [comment]
There is no support for requesting the version-number incl. the build, so you should ask for version=8.0.302 or version=1.8.0_302 or version=8u302

**Comment by repolevedavaj** [comment]
Ah, I was not aware of that. I just tested the version as written on the Temurin download site: https://adoptium.net/releases.html?variant=openjdk8&jvmVariant=hotspot. But in this case, I would expect to always receive an empty result, which is currently not the case.
