### ISSUE TITLE
Occasional HTTP 504 error

### ISSUE THREAD

**Issue by marchof** [foojayio/discoapi#45]
I run a nightly CI build to sync javaalmanac.io data with disco API (basically to find out whether a certain distro is available on the disco API)

Almost every night (at 01:00 UTC) the following query fails:

`java.io.IOException: Server returned HTTP response code: 504 for URL: https://api.foojay.io/disco/v2.0/packages?version=11&distro=semeru&latest=available`

If I trigger the build again in the morning it works again.

**Comment by HanSolo** [comment]
Should be fixed in the meantime

**Comment by marchof** [comment]
I can confirm! Thx.

**Comment by marchof** [comment]
504 is back since tonight:

    java.io.IOException: Server returned HTTP response code: 504 for URL: https://api.foojay.io/disco/v2.0/packages?version=15&distro=zulu&latest=available

**Comment by HanSolo** [comment]
Yep I saw that too, was your call around 11:30pm?

**Comment by marchof** [comment]
Had two failures so far:

- Nov 09, 2021 2:02:44 AM
- Nov 09, 2021 10:04:31 AM

I guess GitHub action tiestamps are in UTC.

**Comment by HanSolo** [comment]
Hmm...ok...good to know...thx a lot 👍🏻

**Comment by marchof** [comment]
Still getting random 400, 502 and 504 responses. Examples: 

    Fri, 12 Nov 2021 02:03:03 GMT java.io.IOException: Server returned HTTP response code: 502 for URL: https://api.foojay.io/disco/v2.0/packages?version=11&distro=temurin&latest=available
    Fri, 12 Nov 2021 09:40:40 GMT java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.foojay.io/disco/v2.0/packages?version=10&distro=sap_machine&latest=available
    Fri, 12 Nov 2021 09:44:15 GMT java.io.IOException: Server returned HTTP response code: 504 for URL: https://api.foojay.io/disco/v2.0/packages?version=11&distro=dragonwell&latest=available

**Comment by HanSolo** [comment]
Made some changes over the weekend, would be great if you could check again if the problem still exists.

**Comment by marchof** [comment]
Indeed, build was green tonight, thx! I'll keep an eye on it.
