### ISSUE TITLE
Unclear what the difference is between c_std_lib / glibc / libc

### ISSUE THREAD

**Issue by mikehearn** [foojayio/discoapi#47]
I only know of two C libaries used in the Linux world, glibc and musl. What do "c_std_lib" and "libc" mean?

**Comment by HanSolo** [comment]
libc -> MacOS
glibc -> Linux
musl -> Linux (Alpine Linux)
c_std_lib -> Windows

**Comment by mikehearn** [comment]
It's probably worth noting that in the docs. C Libraries aren't really relevant on other operating systems: macOS only has one, and on Windows you normally bundle it with the app.

**Comment by HanSolo** [comment]
But they are relevant for the api to determine between Linux + musl and Linux + glibc. And for that reason we keep this info for all operating systems
