### ISSUE TITLE
Zulu JDK 8 on macos are missing from the API response

### ISSUE THREAD

**Issue by yogurtearl** [foojayio/discoapi#50]
The response from:  
https://api.foojay.io/disco/v2.0/packages/jdks?version=8&operating_system=macos

Should include these JDKs: 
https://www.azul.com/downloads/?version=java-8-lts&os=macos&package=jdk

**Comment by HanSolo** [comment]
Hmm…looks like you‘ve found a missing package…will check that, thx for the heads up 👍🏻

**Comment by HanSolo** [comment]
I've checked the Azul CDN and it looks like the first version of JDK 8 that was available for MACOS was 8.0.5 which is available in Disco too. Also checked the Zulu API (https://api.azul.com/zulu/download/community/v1.0/bundles/?java_version=8.0.0&os=macos) and it does not return any bundle. So it seems Disco is right :)

Just to make that clear, you asked for JDK 8.0.0 in your request and that is not available for MacOS BUT if you are looking for  the latest available packages from JDK 8 you need to add &latest=available to you request. You could also ask for a range of versions e.g. version=8..<9 which will give you all version from 8 til 9 (excluding 9) or e.g. version=8.0.212..<8.0.292
