### ISSUE TITLE
Cannot request package info for GraalVM CE with distribution name "Graal VM CE XX"

### ISSUE THREAD

**Issue by repolevedavaj** [foojayio/discoapi#51]
If I try to request the package info for a specific GraalVM distribution with "Graal VM CE XX" as distribution name, I get a 400 status. If I use "GraalVM CE XX" as name, it works. According to https://api.foojay.io/disco/v2.0/distributions?include_versions=false, "Graal VM CE XX" is the official name and "GraalVM CE XX" just a synonym.

**Comment by HanSolo** [comment]
The api_parameter in the response from https://api.foojay.io/disco/v2.0/distributions?include_versions=false is the value that should be used for the query

**Comment by repolevedavaj** [comment]
Ah I see. Thanks for the quick feedback!

**Comment by sschuberth** [comment]
Hmm, so while `graalvm_ce11` is listed as an `api_parameter`, https://api.foojay.io/disco/v3.0/packages?distro=graalvm_ce11 says "No package(s) found". Is this expected? Because for some other distro like https://api.foojay.io/disco/v3.0/packages?distro=oracle_open_jdk it seems to work.

**Comment by HanSolo** [comment]
Hmm...that's not correct, thx for the heads up, will take a look at it 👍🏻

**Comment by jbartok** [comment]
For my own clarification: is the right/recommended way of setting the `distro` param for packages using the `api_parameter` or the `name` of distributions?

**Comment by sschuberth** [comment]
The `api_parameter` should be used, see [above](https://github.com/foojayio/discoapi/issues/51#issuecomment-1002919411).

**Comment by HanSolo** [comment]
Already found the issue, it is related to the introduction of graalvm early access builds, will fix it asap and will close this issue as soon as it will be working as expected and be available in production.

**Comment by sschuberth** [comment]
> will close this issue as soon as it will be working as expected and be available in production.

Thanks! However, then you should probably reopen this issue first :grin:

**Comment by sschuberth** [comment]
Looking good to me now, thanks a lot for the fast fix @HanSolo!

**Comment by HanSolo** [comment]
Great, thx again for the report and testing 👍🏻😁
