### ISSUE TITLE
sap-machine versions 12-16 not listed any more

### ISSUE THREAD

**Issue by marchof** [foojayio/discoapi#54]
Hi, I noticed that the SAP distributions 12, 13, 14, 15, 16 are not reported any more by the API while they are still available:

https://sap.github.io/SapMachine/latest/12
https://sap.github.io/SapMachine/latest/13
https://sap.github.io/SapMachine/latest/14
https://sap.github.io/SapMachine/latest/15
https://sap.github.io/SapMachine/latest/16

**Comment by HanSolo** [comment]
We had some hickup last Friday, will check tomorrow 👍🏻

**Comment by HanSolo** [comment]
They should be back again...

**Comment by marchof** [comment]
Yes, fixed now, thanks!
