### ISSUE TITLE
discoapi not returning all versions for Mandrel

### ISSUE THREAD

**Issue by zakkak** [foojayio/discoapi#56]
Running:

```
curl 'https://api.foojay.io/disco/v3.0/distributions/mandrel' | jq 
```

Returns:
```
{
  "result": [
    {
      "name": "Mandrel",
      "api_parameter": "mandrel",
      "maintained": true,
      "official_uri": "https://developers.redhat.com/blog/2021/04/14/mandrel-a-specialized-distribution-of-graalvm-for-quarkus#",
      "versions": [
        "22.0.0.2",
        "21"
      ]
    }
  ],
  "message": ""
}
```

Which is missing the latest `22.1.0.0` release and lists a non existing 21 release, while it should list `21.3.2.0` instead.

I tried compiling the discoapi repository to run some tests and figure out what might be wrong, but `./gradlew run` fails with:

```
Error: Could not find or load main class io.foojay.Application
Caused by: java.lang.ClassNotFoundException: io.foojay.Application
```

**Comment by HanSolo** [comment]
I will take a look at it, thx for the heads up 👍🏻

**Comment by HanSolo** [comment]
Yes you are right, there are a couple of pkgs missing from Mandrel. I checked the code and it finds the packages but they do not appear in the database, will further investigate.

**Comment by HanSolo** [comment]
Found and fixed the issue, so the pkgs should be available soon in production. If this fixed your issue, please close it.

**Comment by HanSolo** [comment]
there is a parameter called jdk_version that takes an in e.g. &jdk_version=11 should return all versions based on jdk11…hopefully 😁

**Comment by zakkak** [comment]
Great,  thanks!
