### ISSUE TITLE
Loom packages have hundreds of `loom` tags

### ISSUE THREAD

**Issue by marchof** [foojayio/discoapi#58]
# Steps to reproduce

Submit this query: https://api.foojay.io/disco/v3.0/packages?distro=oracle_open_jdk&version=19-ea&package_type=jdk&operating_system=linux&architecture=x64,amd64&latest=available

# Expected Behavior

For loom builds the feature `loom` is only reported once.

# Actual Behaviour

The `loom` feature is reported > 500 times.

![image](https://user-images.githubusercontent.com/1936262/173416685-fd189c36-74f9-4c54-b7a4-e9089c825717.png)

**Comment by HanSolo** [comment]
Ups…thx for the heads up…will check tomorrow 👍🏻

**Comment by marchof** [comment]
Not a problem for me at all. I just noticed that this causes huge response payloads.

**Comment by HanSolo** [comment]
There was a problem with the features in general, not only loom but also panama, valhalla and others. Will be fixed with next deployment.
