### ISSUE TITLE
Oracle OpenJDK 9.0.4 has vanished from the results

### ISSUE THREAD

**Issue by mikehearn** [foojayio/discoapi#59]
https://download.java.net/java/GA/jdk9/9.0.4/binaries/openjdk-9.0.4_osx-x64_bin.tar.gz exists and was previously reported by the API but no longer is. What happened to the 9.0.4 release, and why is it no longer in the reported results?

**Comment by HanSolo** [comment]
will check, thx for the heads-up 👍🏻

**Comment by HanSolo** [comment]
I just checked the api and I found the requested pkg. So can you post the request that failed please?

**Comment by HanSolo** [comment]
Because there was no feedback for 12 days I will close this issue soon because it seems to be not a problem any longer

**Comment by mikehearn** [comment]
It re-appeared in the results, without me doing anything, which is a bit odd.
