### ISSUE TITLE
GraalVM 22.2 missing

### ISSUE THREAD

**Issue by helpermethod** [foojayio/discoapi#61]
Hi!

Despite being available for a few days, GraalVM version 22.2 is missing.

Is this a bug, or is a longer lag to be expected?

**Comment by HanSolo** [comment]
Yes we are aware of that, the pkgs are already in the database but the messaging in the cluster has some hickups at the moment which leads to the missing pkgs in the api

**Comment by helpermethod** [comment]
Thanks for the quick reply!
