### ISSUE TITLE
https://api.foojay.io/disco/v2.0/directuris returns 404

### ISSUE THREAD

**Issue by steve1337** [foojayio/discoapi#62]
Was this endpoint removed from the API?

![image](https://user-images.githubusercontent.com/22643375/181733629-5bd026f6-932a-4f8f-9ade-9e08120e8caa.png)

I cannot install JBANG anymore because of this error

Reference: https://github.com/jbangdev/jbang/issues/1414

**Comment by HanSolo** [comment]
no it was not removed but it seems we have some issues with api at the moment. The infrastructure team is already working on it.

**Comment by steve1337** [comment]
Thanks for the quick response. 

Unfortunately I'm not a maintainer of JBANG and can therefore not make that change. 

But this clears things up. Have a nice weekend!
