### ISSUE TITLE
Latest Liberica NIK releases (22.3.1, 21.3.3.1) not available in Disco API

### ISSUE THREAD

**Issue by dr-eme** [foojayio/discoapi#69]
Hi!

Looks like https://api.foojay.io/disco/v3.0/distributions doesn't contain 22.3.1 nor 21.3.3.1 versions for Liberica Native, released last week.

**Comment by HanSolo** [comment]
Thank's for the heads up, will check what's the problem 👍🏻

**Comment by HanSolo** [comment]
Should be available now

**Comment by dr-eme** [comment]
Indeed, thanks.
