### ISSUE TITLE
https://api.foojay.io/disco/v3.0/directuris down?

### ISSUE THREAD

**Issue by steve1337** [foojayio/discoapi#71]
Are you having an outage or any other problems with the API right now?

JBANG is failing to install the JDK

Ref: https://raw.githubusercontent.com/jbangdev/jbang/master/src/main/scripts/jbang

For future reference do you have a status page for your API? 
Better than opening an issue here each time something happens.

**Comment by steve1337** [comment]
Working again

**Comment by HanSolo** [comment]
Yep I did a deployment which took unexpected long...sorry for that, we are looking into a status page, so stay tuned :)

**Comment by HanSolo** [comment]
Just created a status page on freshping which should help with this: https://statuspage.freshping.io/65319-foojayio
