### ISSUE TITLE
AdoptOpenJDK has moved to Adoptium and Temurin

### ISSUE THREAD

**Issue by kabel** [foojayio/discoapi#72]
The API for versions has changed slightly as eclipse is now the preferred vendor. Currently `aoj` is missing recent jdk versions like 17, 18 and 19.

See https://adoptium.net/

**Comment by HanSolo** [comment]
Yep I know that’s the reason why we have AOJ up to 16.0.2 and Temurin from 17 upwards. AOJ is end of life and just to be clear it’s not the same distribution.

**Comment by kabel** [comment]
Well that's embarrassing. I should have looked/searched closer.
