### ISSUE TITLE
Latest Liberica NIK release 22.3.2 is not available in Disco API

### ISSUE THREAD

**Issue by strizhik** [foojayio/discoapi#73]
Hi!

Looks like the new NIK release cannot be found in foojay api.
https://api.bell-sw.com/v1/nik/releases?version=22.3.2+1

https://api.foojay.io/disco/v3.0/distributions/liberica_native
"22.3.1" is the latest.

Thanks!

**Comment by HanSolo** [comment]
Will take a look, thx for the heads up 👍🏻

**Comment by HanSolo** [comment]
Should be available now...

**Comment by strizhik** [comment]
Thanks!
