### ISSUE TITLE
New "Oracle GraalVM" Distribution Available

### ISSUE THREAD

**Issue by lread** [foojayio/discoapi#75]
Hey ho!

The GraalVM team just released v23 of their Community Edition: https://github.com/graalvm/graalvm-ce-builds/releases/tag/graal-23.0.0. This includes jdk17 and jdk20 variants.
I'm guessing that the disco API will automatically pick this up.

But... there is also now a new "Oracle GraalVM"
https://medium.com/graalvm/a-new-graalvm-release-and-new-free-license-4aab483692f5
Which is downloaded from Oracle:
https://www.oracle.com/java/technologies/jdk-script-friendly-urls/
I expect, if it wishes to make it available, the disco API will need to be updated to learn about this new distribution.

**Comment by HanSolo** [comment]
Just to make it clear it is not GraalVM 23 but GraalVM community 17.0.7 and 20.0.1. 😁 This already in the making and will hopefully be released tomorrow 😁

**Comment by lread** [comment]
Yeah, they released the Community Edition, like they have in the past, the thing we are used to.

But now, also, they have this news "Oracle GraalVM" distribution which is also free (but has a different licence).
Not sure what their grand plan is yet. Not sure if they will eventually phase out the Community Edition.

**Comment by HanSolo** [comment]
Yep and both will be in Disco, there will be graalvm_community and graalvm.

**Comment by lread** [comment]
Thanks @HanSolo, you are the best!

**Comment by lread** [comment]
Ah, now that it is live, I see what you were telling me but that I did not fully absorb.

The new Oracle Graal releases match the JDK version, so we no longer have 2 versions to fiddle with. This is covered by the new `graalvm` distribution.

And new releases of the Community Edition now follow this [same](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-20.0.1) [new](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-17.0.7) scheme.
This is covered by `graalvm_community`.
I did not notice the 23.0.0 CE [downloads](https://github.com/graalvm/graalvm-ce-builds/releases/tag/graal-23.0.0) are now just optional components.
 
Thanks so much, there is no need to keep this one open anymore, but maybe this little discussion will help others to understand the transition.

**Comment by HanSolo** [comment]
Yep, they got rid of all the complexity and followed the OpenJDK versioning scheme. Disco will keep the old GraalVM CE builds as they have been and new builds will be available under graalvm and graalvm_community with the same version numbers that are also used in OpenJDK.
