### ISSUE TITLE
discoapi currently returning empty results

### ISSUE THREAD

**Issue by lread** [foojayio/discoapi#76]
Hiya, I expect you might know about this, but in case you do not, the discoapi seems to be currently returning empty results.

Example: https://api.foojay.io/disco/v3.0/packages/all

Is currently returning:
```json
{"result":[],"message":""}
```

Or this example from the README: https://api.foojay.io/disco/v3.0/packages?package_type=jdk&latest=available&version=11&javafx_bundled=true&operating_system=macos&architecture=x64&archive_type=dmg&archive_type=pkg

```json
{"result":[],"message":"No package(s) found"}
```

**Comment by HanSolo** [comment]
Yep we are running a complete deployment at the moment...should be back again soon...

**Comment by lread** [comment]
Looks happy again, closing!
