### ISSUE TITLE
Filtering `graalvm_community` for `jdk_version` does not seem to work correctly

### ISSUE THREAD

**Issue by sschuberth** [foojayio/discoapi#77]
https://api.foojay.io/disco/v3.0/packages?distro=graalvm_community returns entries with `jdk_version: 20`, but https://api.foojay.io/disco/v3.0/packages?distro=graalvm_community&jdk_version=20 returns "No package(s) found".

**Comment by HanSolo** [comment]
The jdk_version parameter alone is not enough to specify the packages, please try something like: https://api.foojay.io/disco/v3.0/packages?distro=graalvm_community&version=20&latest=available

**Comment by fniephaus** [comment]
@HanSolo shouldn't [this](https://api.foojay.io/disco/v3.0/packages?distro=graalvm_community&jdk_version=20) then show an error that says that `latest` is required when `jdk_version` is used and vice versa? :)

**Comment by sschuberth** [comment]
> The jdk_version parameter alone is not enough to specify the packages

Interesting. I was coming from the request generated [here](https://github.com/gradle/foojay-toolchains/blob/1c3a7c4d5580628d706bb1bdfc1a3e63d3ec875d/foojay-resolver/src/main/kotlin/org/gradle/toolchains/foojay/FoojayApi.kt#L69-L75), seeing that it yields no results for `graalvm_community`, but does e.g. for `temurin`. Also, e.g. https://api.foojay.io/disco/v3.0/packages?distro=temurin&jdk_version=20 just works. Is this expected?

**Comment by HanSolo** [comment]
Well…jdk_version was only introduced because of the different versioning in the former graalvm distributions. Originally disco was only planned for OpenJDK distributions. You should use version instead.

**Comment by sschuberth** [comment]
> You should use version instead.

Just to clarify: Will also requesting old "GraalVM CE 8 *X*"-style distributions work when using `version` instead of `jdk_version`?

**Comment by sschuberth** [comment]
> jdk_version was only introduced because of the different versioning in the former graalvm distributions.

Also, as in the old GraalVM versioning the JDK version is part of the distribution name (like "graalvm_ce11"), what's the `jdk_version` needed for at all?
