### ISSUE TITLE
Latest Liberica NIK release 23.0.0 is not available in Disco API

### ISSUE THREAD

**Issue by strizhik** [foojayio/discoapi#78]
Hi!

Looks like the new NIK release cannot be found in foojay api.
https://api.bell-sw.com/v1/nik/releases?version=23.0.0+1

https://api.foojay.io/disco/v3.0/distributions/liberica_native
"22.3.2" is the latest.

Thanks!

**Comment by HanSolo** [comment]
Hmm...will check, thx for the heads up 👍🏻

**Comment by HanSolo** [comment]
I‘m doing a new deployment right now and on my test system the lates Liberica NIK builds are available. Might take until tomorrow for the packages to appear in the api.

**Comment by HanSolo** [comment]
Did some tests yesterday evening and now they seem to be available.

**Comment by strizhik** [comment]
NIK 23 releases are in place. Thanks!
