### ISSUE TITLE
`No package(s) found` result

### ISSUE THREAD

**Issue by remal** [foojayio/discoapi#79]
This URL returns `{"result":[],"message":"No package(s) found"}`: https://api.foojay.io/disco/v3.0/packages?version=17&distro=temurin

I tried different versions (9, 11) with the same result.

And even the URL from documentation returns the same empty response: https://api.foojay.io/disco/v3.0/packages?package_type=jdk&latest=available&version=11&javafx_bundled=true&operating_system=macos&architecture=x64&archive_type=dmg&archive_type=pkg

**Comment by HanSolo** [comment]
Should be back again…could you quickly check?

**Comment by HanSolo** [comment]
Might take some time until the latest pkgs will appear because the db had a problem and needed a “reset”. Now the scanning for new pkgs might be a bit behind but should catch up.

**Comment by HanSolo** [comment]
Seems to be fixed again, so I will close it 😁
