### ISSUE TITLE
API doesn't return valuable responses

### ISSUE THREAD

**Issue by strizhik** [foojayio/discoapi#80]
Hi,
It looks like API doesn't response properly.
Even examples from documentation returns empty result.

For example:
https://api.foojay.io/disco/v3.0/packages?package_type=jdk&latest=available&version=11&javafx_bundled=true&operating_system=macos&architecture=x64&archive_type=dmg&archive_type=pkg

```
{
"result": [],
"message": "No package(s) found"
}
```

https://api.foojay.io/disco/v3.0/ids/2dd07b11553c798fa49274d937ba88e9

```
{
"result": [],
"message": "Package id not found"
}
```

I think this is similar to #79

**Comment by solidjb** [comment]
I agree.  Something seems to have happened to the data

https://api.foojay.io/disco/v3.0/distributions/oracle_open_jdk - > returns no versions

https://api.foojay.io/disco/v3.0/distributions/versions/17?include_versions=false&include_synonyms=false -> only returns zulu, temurin and zulu_prime

**Comment by geertjanw** [comment]
No worries, I'm sure @HanSolo will investigate and respond soon.

**Comment by HanSolo** [comment]
Yep we encounter some strange behavior with the database and already looking into it…

**Comment by HanSolo** [comment]
Sorry for the inconvenience but it looks like we are back on track…

**Comment by strizhik** [comment]
Yeah, looks like the api feels better now :)
Thanks a lot!

**Comment by HanSolo** [comment]
Thx for reporting the issue 👍🏻
