### ISSUE TITLE
Latest Liberica NIK releases 22.3.3 and 23.0.1 are not available in Disco API

### ISSUE THREAD

**Issue by strizhik** [foojayio/discoapi#82]
Hi!

Looks like the new NIK releases cannot be found in foojay api.
https://api.bell-sw.com/v1/nik/releases?version=22.3.3+1
https://api.bell-sw.com/v1/nik/releases?version=23.0.1+1

https://api.foojay.io/disco/v3.0/distributions/liberica_native
"23" and "22.3.2" are the latest.

Thanks!

**Comment by HanSolo** [comment]
I’m currently on vacation but will check when back home. It might also take some time for the api to pick up these builds because the focus is on builds of OpenJDK and not GraalVM.

**Comment by strizhik** [comment]
I still do not see 23.0.1 and 22.3.3 in the response from https://api.foojay.io/disco/v3.0/distributions/liberica_native

**Comment by HanSolo** [comment]
I do see them now when following the provided link, could you check again please?

**Comment by strizhik** [comment]
Yes, new releases are in place now. Thanks!
