### ISSUE TITLE
API returns 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by florianmutter** [foojayio/discoapi#85]
Right now the API return 503 Service Temporarily Unavailable

```bash
$ curl "https://api.foojay.io/disco/v3.0/packages?package_type=jdk&latest=available&version=11&javafx_bundled=true&operating_system=macos&architecture=x64&archive_type=dmg&archive_type=pkg" 
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by HanSolo** [comment]
Yep, saw that too, we already investigate what’s going on, thx for the heads-up 👍🏻

**Comment by tinder-ryantrontz** [comment]
Is there anywhere we should be looking for status updates on this?

**Comment by HanSolo** [comment]
No there isn’t a status page, we are still working on it…

**Comment by HanSolo** [comment]
Should be back online

**Comment by petersononyeukwu-asurion** [comment]
I ran into this issue earlier since I was downloading jbang on a new system. But I can confirm that it's working now.
