### ISSUE TITLE
How to correctly select Java 21 Distributions?

### ISSUE THREAD

**Issue by marchof** [foojayio/discoapi#86]
While updating https://javaalmanac.io for the Java 21 I encountered the following issue. If I search with the following query:

    https://api.foojay.io/disco/v3.0/packages?version=21&package_type=jdk&latest=available

I get mostly Graal implementations (which is currently 21.x.y). So I tried the parameter `java_version` instead, as the README.md suggests: 

    https://api.foojay.io/disco/v3.0/packages?java_version=21&package_type=jdk&latest=available

Unfortunetelly this leads to an `504 Gateway Time-out`.

My questions are:

* What is the correct way to query for Java feature version 21?
* Is there still an OpenAPI / Swagger frontend to see the API documentation?

**Comment by marchof** [comment]
I re-discovered the [swagger-ui](https://api.foojay.io/swagger-ui#/default/getPackagesV3). Some more insights:

* Looks like the `java_version` parameter mentioned in README.md does not exist.
* Whenever you specify a unknown parameter a `504 Gateway Time-out` is returned after some time.

**Comment by geertjanw** [comment]
I’m sure Gerrit will investigate and report back here soon.

**Comment by HanSolo** [comment]
Will take a look at it as soon as I’ll have some time, thx for the report 👍🏻

**Comment by marchof** [comment]
Looks like `jdk_version` is now magically working the the `503` responses are gone:

    https://api.foojay.io/disco/v3.0/packages?jdk_version=21&package_type=jdk&latest=available

@HanSolo Can you confirm this is the correct way to go?
